name: 05-1-filters-activity-types.yaml

no: 
    workflow_dispatch
    pull_request 
      types: [open, synchronize]
      branches:
        - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps: 
            -run: echo "Running whenever a PR is opened or synchronized AND Base branch is main." 
