name: 05-2-filters-activity-types.yaml

no: 
    workflow_dispatch
    pull_request 
      types: [close, synchronize]
      branches:
        - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps: 
            -run: echo "Running whenever a PR is closed or synchronized AND Base branch is main." 
