name: 03b -Workflow Runners

on:
    workflow_dispatch

jobs:
    ubunto-echo:
    runs-on: ubuntu-latest
    steps:
        - name: show OS
          run: |
            echo "this job is running on Ubuntu-runner"
            echo " runner OS: $runner_os"


