name: 03b -Workflow Runners

on: workflow_dispatch

jobs:
  ubunto-echo:
    runs-on: ubuntu-latest
    steps:
      - name: show OS
        run: |
          echo "this job is running on Ubuntu-runner"
          echo " runner OS: $RUNNER_OS"
  window-echo:
    runs-on: windows-latest
    steps:
      - name: show Os
        shell: bash
        run: |
          echo "this job is running on windows-runner"  
          echo "runner Os: $RUNNER_OS"
  mac-echo:
    runs-on: macos-latest
    steps:
      - name: show Os
        run: |
          echo "this job is running on a MacOS runner."
          echo "runner os: $RUNNER_OS"