name: 04-using-actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        defaults: 
          run: 
            working-directory: .github/workflows/04-using-actions/react-app
        steps:
            - name: checkout Code
              uses: actions/checkout@v4 
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: '22.x' 
            - name: Install Dependencies
              run: npm ci
              working-directory: .github/workflows/04-using-actions/react-app
        
        #0.
        #1. installs deps of our react applicaiton
        #2. Execute automated tests
        
