name: 15 - Working with Matrices

on: 
    workflow_dispatch: 

jobs: 
    backward-compatibility:
      name: ${{ matrix.os }}-${{ matrix.node-version }}
      strategy: 
        matrix: 
          node: [18.x, 20.x, 21.x]
           os: 
            - ubuntu-latest
            - window-latest
        include: 
            - os: ububntu-latest
              node: 16.x
              tag: experimetnal
              fail-fast: false
            - os: ubuntu-latest
              node: 21.x
      runs-on: ${{ matrix.os }}
      steps: 
        - name: Setup node
          uses: actions/setup-node@v3
          with: 
            node-version: ${{ matrix.node-version}}
        - name: Perform Some test
          run: echo " running tests on OS ${{ matrix.os }} and nodeJS ${{ matrix.node-version }}"

        