name: 17 - 2 - Custom Actions - Composite

on: 
  workflow_dispatch: 
   

  
env:
  working-directory: ./your-default-directory
  
jobs: 
  dependency-update:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ${{ env.working-directory }}
    steps: 
      - uses: actions/checkout@v4
      - name: Check for dependency updates
        uses: ./.github/actions/js-dependency-update
        