name: 18 - 2 - Reusable Workflows

on: 
workflow_dispatch: 

jobs: 
  deploy: 
    uses: ./.github/workflows/18-1-resuable-workflows.yaml
    with: 
      target-directory: dummy-dir
  print-outs: 
    runs-on: ubuntu-latest
    needs: deploy
    steps: 
      - name: Print outputs
        run: |
          echo: "Build status: ${{ needs.build.outputs.build-status }}"
          echo: "URL: ${{ needs.deploy.outputs.url }}"